### ISSUE TITLE
Surface the Entrypoint of a Contour in Status

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#184]
**Please describe the problem you have**
Reflect entrypoint/ingress details in the status of a Contour. Similar to [ingress](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#loadbalanceringress-v1-core) of a service resource. For example:

```
apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: example
status:
  ingress:
    ip: <service_ip>
    ports:
    - 80
    - 443
```

Implementation considerations:
- Nodeport service would need to surface every worker node IP in the cluster.
- Should a `hostname` field be included that external DNS could populate?
