### ISSUE TITLE
Figure Out How to Handle Operator Patch Releases

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#192]
**Please describe the problem you have**
An operator patch release will be cut when a contour patch release is cut. If Contour v1.11.1 is cut, contour-operator v1.11.1 will be cut to include the appropriate contour/envoy patched images. This is what the operator's deployment manifests will look like using v1.11.1 as a patch release example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contour-operator
  namespace: system
  labels:
    control-plane: contour-operator
spec:
  selector:
    matchLabels:
      control-plane: contour-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: contour-operator
    spec:
      containers:
      - command:
        - /contour-operator
        - --contour-image
        - docker.io/projectcontour/contour:v1.11.1
        - --envoy-image
        - docker.io/envoyproxy/envoy:v1.16.2
<SNIP>
```

__Note:__ Only the Contour image is updated in the above example.

However, what if only the operator needs a patch release? Should a patched version of Contour be cut even though it includes no changes so that the versions continue to be synchronized?

cc: @skriss @youngnick @Miciah
