### ISSUE TITLE
Make LoadBalancerStarategy Optional

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#279]
**Please describe the problem you have**
Currently, "LoadBalancerStrategy" is being defaulted for Envoy network publishing. This is fine when using the "LoadBalancerService" type (default), but does not make sense when using other network publishing types. For example (NodePortService):

```
spec:
  namespace:
    name: projectcontour
    removeOnDeletion: false
  networkPublishing:
    envoy:
      containerPorts:
      - name: http
        portNumber: 8080
      - name: https
        portNumber: 8443
      loadBalancer:
        providerParameters:
          type: AWS
        scope: External
      type: NodePortService
  replicas: 2
```
