### ISSUE TITLE
operator does not create envoy service with ClusterIPService type and gatewayClassRef

### ISSUE THREAD

**Issue by nak3** [projectcontour/contour-operator#291]
**What steps did you take and what happened:**

#### 0. Deploy operator

```
$ kubectl apply -f examples/operator/operator.yaml 
```

#### 1. Deploy contour CR with ClusterIPService and gatewayClassRef.

Create `examples/gateway/gateway.yaml` with following Contour CR.

```
apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: contour-gateway-sample
  namespace: contour-operator
spec:
  gatewayClassRef: sample-gatewayclass
  networkPublishing:
    envoy:
      type: ClusterIPService
```

#### 2. envoy service is not created.

```
$ kubectl get svc -n projectcontour
NAME      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
contour   ClusterIP   172.20.21.30   <none>        8001/TCP         2m55s
```

**What did you expect to happen:**

- envoy service should be created.

**Environment:**

- operator build on 433691b0abddb15cfdd728c478b10b5db0e3db6c
