### ISSUE TITLE
Pass annotations to created resource

### ISSUE THREAD

**Issue by BostjanBozic** [projectcontour/contour-operator#327]
**Please describe the problem you have**
It would be great if there would be a possibility to pass annotations to created objects, preferably on object level.

An example of usage:
* create `Contour` custom resource
```
apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: contour
spec:
  namespace:
    name: projectcontour
  networkPublishing:
    envoy:
      type: LoadBalancerService
      loadBalancer:
        annotation:
          service.beta.kubernetes.io/azure-load-balancer-resource-group: test-group
        scope: External
        providerParameters:
          type: Azure
```
* Following service is created
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: test-group
  name: envoy
  namespace: projectcontour
spec:
  loadBalancerIP: <IP>
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: envoy
  type: LoadBalancer
```

Example use case: use existing public IP created on Azure for envoy service.

**Comment by danehans** [comment]
`providerParameters` is meant as the mechanism for passing provider-specific parameters. To provide a more predictable user experience, I prefer adding fields to `providerParameters` instead of passing annotations from the API to the Envoy Service resource directly. Your example could look something like:
```
apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: contour
spec:
  namespace:
    name: projectcontour
  networkPublishing:
    envoy:
      type: LoadBalancerService
      loadBalancer:
        scope: External
        # Optional- Assign a static IP to the LB (auto assigned by cloud provider by default).
        # This address should be from resource group "my-lb-public-ips".
        # xref: https://github.com/projectcontour/contour-operator/pull/336
        address: 200.200.200.200
        providerParameters:
          type: Azure
          azure:
            # Optional- Specifies the resource group of load balancer public IPs that aren't in the same
            # resource group as the cluster infrastructure (node resource group by default).
            resourceGroup: my-lb-public-ips
```

The result is the following Envoy Service resource is created:
```
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: my-lb-public-ips
  name: envoy
  namespace: projectcontour
spec:
  loadBalancerIP: 200.200.200.200
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: envoy
  type: LoadBalancer
```

From reading the [Azure LB docs](https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard), it's unclear if you can specify an IP for an internally-scoped LB. This should be investigated further. I suggest manually creating an internal LB that has a static address so we understand what, if any, combination of provider-specific annotations are required. 

It appears that GCP [supports](https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing) assigning an IP to an internally-scoped LB. An internally-scoped LB with a static IP could look something like:
```
apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: contour
spec:
  namespace:
    name: projectcontour
  networkPublishing:
    envoy:
      type: LoadBalancerService
      loadBalancer:
        scope: Internal
        # Optional- The address must be within the user-defined "gke-vip-subnet" network.
        # If unspecified, an address is auto-assigned by the provider from "gke-vip-subnet".
        # xref: https://github.com/projectcontour/contour-operator/pull/336
        address: 10.10.10.10
        providerParameters:
          type: GCP
          gcp:
            # Optional- Specifies from which subnet the LB IP should be provisioned from.
            # This subnet must exist in GCP.
            subnet: gke-vip-subnet
```

The result is the following Envoy Service resource is created:
```
kind: Service
metadata:
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-subnet: "gke-vip-subnet"
  name: envoy
  namespace: projectcontour
spec:
  loadBalancerIP: 10.10.10.10
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: envoy
  type: LoadBalancer
```

We need to think through how adding support for specifying an LB IP a) works across the supported cloud providers (AWS, GCP and Azure) and b) works with an internally-scoped LB. Instead of working through these details through GH comments, I think a design doc should be created. The doc can be a simple google doc that answers these questions and outlines API changes, controller changes, etc..
