### ISSUE TITLE
Contour pod and Gateway must be deployed in the same namespace?

### ISSUE THREAD

**Issue by nak3** [projectcontour/contour-operator#343]
**What steps did you take and what happened:**

#### 1. Install operator from main branch.

```
kubectl apply -f "https://raw.githubusercontent.com/projectcontour/contour-operator/main/examples/operator/operator.yaml"
```

#### 2. Install Contour and Gateway in different namespaces.

- Gateway is deployed in `knative-serving` namespace.
- Contour is deployed in `contour-external` namespace.

```
cat <<-EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: contour-operator
  name: contour-external
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: contour-operator
  name: knative-serving
---
apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: contour-external
  namespace: contour-external
spec:
  gatewayClassRef: contour-external-gatewayclass
  namespace:
    name: contour-external
  ingressClassName: contour-external
  networkPublishing:
    envoy:
      type: LoadBalancerService
---
kind: GatewayClass
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: contour-external-gatewayclass
spec:
  controller: projectcontour.io/contour-operator
  parametersRef:
    group: operator.projectcontour.io
    kind: Contour
    scope: Namespace
    name: contour-external
    namespace: contour-external
---
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: test-gateway
  namespace: knative-serving
spec:
  gatewayClassName: contour-external-gatewayclass
  listeners:
  - protocol: HTTP
    port: 80
    routes:
      kind: HTTPRoute
      selector:
        matchLabels:
          knative-e2e-test: "net-ingressv2"
      namespaces:
        from: "All"
EOF
```

#### 3. contour pod fails to start.

```
$ kubectl get  -n contour-external  pod contour-8846b749f-7b6bc
NAME                      READY   STATUS              RESTARTS   AGE
contour-8846b749f-7b6bc   0/1     ContainerCreating   0          24m
```

This happens because `contour-config` is deployed in Gateway's namespace.

```
$ kubectl describe -n contour-external  pod contour-8846b749f-7b6bc
  ...
  contour-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      contour
    Optional:  false
  Warning  FailedMount  4m30s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[contour-config], unattached volumes=[contour-token-xxvck contourcert contour-config]: timed out waiting for the condition
```

The ConfigMap is deployed in `knative-serving` namespace.

```
$ kubectl get cm  -n knative-serving contour -o yaml
  ...
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-03T03:51:01Z"
  labels:
    contour.operator.projectcontour.io/owning-gateway-name: test-gateway
    contour.operator.projectcontour.io/owning-gateway-namespace: knative-serving
  name: contour
  namespace: knative-serving
```

**What did you expect to happen:**

- Contour pod and Gateway could be deployed in the different namespace.
- If they must be deployed in the same namespace, multiple Gateway cannot be deployed in one namespace as Contour pod from one Contour CR could be deployed in the one namespace as https://github.com/projectcontour/contour-operator/issues/18. 

**Anything else you would like to add:**

Contour status become `Ready` even contour pod is not running. I think it should be fixed as well. https://github.com/projectcontour/contour-operator/issues/344 is opened for it.
