### ISSUE TITLE
Contour CR with `spec.gatewayClassRef` becomes Ready status even when contour pod is not Ready

### ISSUE THREAD

**Issue by nak3** [projectcontour/contour-operator#344]
**What steps did you take and what happened:**

(This is exact same steps with https://github.com/projectcontour/contour-operator/issues/343)

#### 1. Install operator from main branch.

```
kubectl apply -f "https://raw.githubusercontent.com/projectcontour/contour-operator/main/examples/operator/operator.yaml"
```

#### 2. Install Contour and Gateway in different namespaces.

- Gateway is deployed in `knative-serving` namespace.
- Contour is deployed in `contour-external` namespace.

```
cat <<-EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: contour-operator
  name: contour-external
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: contour-operator
  name: knative-serving
---
apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: contour-external
  namespace: contour-external
spec:
  gatewayClassRef: contour-external-gatewayclass
  namespace:
    name: contour-external
  ingressClassName: contour-external
  networkPublishing:
    envoy:
      type: LoadBalancerService
---
kind: GatewayClass
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: contour-external-gatewayclass
spec:
  controller: projectcontour.io/contour-operator
  parametersRef:
    group: operator.projectcontour.io
    kind: Contour
    scope: Namespace
    name: contour-external
    namespace: contour-external
---
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: test-gateway
  namespace: knative-serving
spec:
  gatewayClassName: contour-external-gatewayclass
  listeners:
  - protocol: HTTP
    port: 80
    routes:
      kind: HTTPRoute
      selector:
        matchLabels:
          knative-e2e-test: "net-ingressv2"
      namespaces:
        from: "All"
EOF
```

#### 3. contour pod fails to start due the issues/343

```
$ kubectl get  -n contour-external  pod contour-8846b749f-7b6bc
NAME                      READY   STATUS              RESTARTS   AGE
contour-8846b749f-7b6bc   0/1     ContainerCreating   0          24m
```

But both Contour and Gateway become __Ready__ status.

```
$ kubectl  -n contour-external get contour
NAME               READY   REASON
contour-external   True    GatewayClassAdmitted

$ kubectl  -n knative-serving describe gateway
  ...
Status:
  Conditions:
    Last Transition Time:  2021-05-03T01:58:15Z
    Message:               The Gateway is ready to serve routes.
    Reason:                GatewayReady
    Status:                True
    Type:                  Ready
```

**What did you expect to happen:**

Contour should not become Ready if Contour pod is not running.
