### ISSUE TITLE
contour pod from multiple CR in the same namespace is conflicted

### ISSUE THREAD

**Issue by nak3** [projectcontour/contour-operator#345]
**What steps did you take and what happened:**

#### 1. Install operator from main branch.

```
kubectl apply -f "https://raw.githubusercontent.com/projectcontour/contour-operator/main/examples/operator/operator.yaml"
```

#### 2. Install Contour (contour-internal and contour-external) in knative-serving namespace

Deploy contour-external

```
cat <<-EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: contour-operator
  name: knative-serving
---
apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: contour-external
  namespace: knative-serving
spec:
  gatewayClassRef: contour-external-gatewayclass
  namespace:
    name: knative-serving
  ingressClassName: contour-external
  networkPublishing:
    envoy:
      type: LoadBalancerService
---
kind: GatewayClass
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: contour-external-gatewayclass
spec:
  controller: projectcontour.io/contour-operator
  parametersRef:
    group: operator.projectcontour.io
    kind: Contour
    scope: Namespace
    name: contour-external
    namespace: knative-serving
---
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: test-gateway
  namespace: knative-serving
spec:
  gatewayClassName: contour-external-gatewayclass
  listeners:
  - protocol: HTTP
    port: 80
    routes:
      kind: HTTPRoute
      selector:
        matchLabels:
          knative-e2e-test: "net-ingressv2"
      namespaces:
        from: "All"
EOF
```

Deploy contour-internal

```
cat <<-EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: contour-operator
  name: knative-serving
---
apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: contour-internal
  namespace: knative-serving
spec:
  gatewayClassRef: contour-internal-gatewayclass
  namespace:
    name: knative-serving
  ingressClassName: contour-internal
  networkPublishing:
    envoy:
      type: ClusterIPService
---
kind: GatewayClass
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: contour-internal-gatewayclass
spec:
  controller: projectcontour.io/contour-operator
  parametersRef:
    group: operator.projectcontour.io
    kind: Contour
    scope: Namespace
    name: contour-internal
    namespace: knative-serving
---
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: test-local-gateway
  namespace: knative-serving
spec:
  gatewayClassName: contour-internal-gatewayclass
  listeners:
  - protocol: HTTP
    port: 80
    routes:
      kind: HTTPRoute
      selector:
        matchLabels:
          knative-e2e-test: "net-ingressv2-local"
      namespaces:
        from: "All"
EOF
```

#### 3. contour pod start running but only from contour-external Contour CR

```
$ kubectl  get pod -n knative-serving
NAME                         READY   STATUS      RESTARTS   AGE
contour-8846b749f-26gvk      1/1     Running     0          4m41s
contour-8846b749f-mrq5p      1/1     Running     0          4m41s
contour-certgen-main-4w66r   0/1     Completed   0          4m41s
envoy-5g699                  2/2     Running     0          4m41s
```

But both contour pods have `--ingress-class-name=contour-external`, not have `--ingress-class-name=contour-internal`

```
$ kubectl  describe pod -n knative-serving contour-8846b749f-26gvk |grep ingress-class
      --ingress-class-name=contour-external
```

**What did you expect to happen:**

In above case, there are 4 contour pods running the half of them have `--ingress-class-name=contour-external` and the rest of them have `--ingress-class-name=contour-internal`.
