### ISSUE TITLE
Operator should allow setting AWS ELB/NLB annotations

### ISSUE THREAD

**Issue by xaleeks** [projectcontour/contour-operator#399]
I’d like to be able to pass annotations for the AWS ELB (https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/) down to the load balancer.  The annotations are typically defined on the service object itself but since the service for the LB is created and managed by the Operator, it’d be good to be able to declaratively set these instead of patching after the object is deployed. 

Imagine something like

```
spec:
 gatewayClassRef: vdp-contour-int
 ingressClassName: vdp-contour-int
 networkPublishing:
   envoy:
     type: LoadBalancerService
     loadBalancer:
       annotations:
         service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
         service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
         service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
       providerParameters:
         type: AWS
       scope: Internal

```
