### ISSUE TITLE
Conditionally Expose the Contour Debug Network Port

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#46]
**Please describe the problem you have**
Currently, the Contour `Deployment` [example](https://github.com/projectcontour/contour/blob/main/examples/contour/03-contour.yaml), exposes the debug network port. This is not required and should be exposed conditionally. For example:

```
...
name: contour
ports:
- containerPort: 8000
  name: debug
  protocol: TCP
...
```

/cc @stevesloka @jpeach @Miciah
