### ISSUE TITLE
contour/envoy container images should come from CRD

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/contour-operator#55]
The image version that is used for Contour/Envoy are taken from an command line arg to the operator, but the operator should be able to derive the information from the Contour-Operator CRD such than different instance of Contour can run their own version requested via the CRD.

_Originally posted by @danehans in https://github.com/projectcontour/contour-operator/pull/44#discussion_r505921582_

**Comment by Miciah** [comment]
In `config/manager/manager.yaml`, we should be using environment variables such as `CONTOUR_IMAGE` and `ENVOY_IMAGE`, and interpolating those into the command like, something like the following:

```yaml
      containers:
      - name: manager
        command:
        - /contour-operator
        args:
        - --enable-leader-election
        - --contour-image
        - "$(CONTOUR_IMAGE)"
        - --envoy-image
        - "$(ENVOY_IMAGE)"
        env:
          - name: CONTOUR_IMAGE
            value: oldX
          - name: ENVOY_IMAGE
            value: oldY
```

And in `kustomization.yaml`, we should replace the values for those variables:

```yaml
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: CONTOUR_IMAGE
              value: newX
            - name: ENVOY_IMAGE
              value: newY
```

Reference:  https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html

@stevesloka, @skriss, @jpeach, does this approach look reasonable?
