### ISSUE TITLE
Support the /scale subresource

### ISSUE THREAD

**Issue by Miciah** [projectcontour/contour-operator#72]
The contour CRD should define the [`/scale` subresource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#subresources) to enable the use of tools such as `kubectl scale` and HPA with contour CRs.

The CRD needs to provide the following information under its `status` field:

* Label selector for the scalable resource (Contour pods).
* Number of available replicas.

`/scale` therefore depends on the `/status` subresource (xref: https://github.com/projectcontour/contour-operator/issues/60).

The CRD also needs to provide the following under its `spec` field:

* Number of desired replicas.

Once this information is available, the CRD can define the `/status` subresource as follows:

```yaml
    subresources:
      scale:
        labelSelectorPath: .status.selector
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.contourReplicasAvailable
```

Post-v1alpha1.
